In [5]:
import requests
from bs4 import BeautifulSoup as bs


In [6]:
url='http://sh.58.com/qiuzu/30745656926008x.shtml?addtype=topinfo&iuType=z_2&PGTID=0d30000b-0000-2615-5e05-78002b71a7f7&ClickID=4&adtype=3'
re=requests.get(url)
soup=bs(re.text,'lxml')
ph=soup.select('#t_phone')
num=ph[0].contents[0]    #单个ｌｉｓｔ，可以用ph【０】，而循环不行，记住了
print(num)


IndexError: list index out of range

In [ ]:
a=10
b=2
try:
    c=a/b
    print(c)
except:
    print('除数不能为０')
print("done")

In [ ]:
a=['1','2','3']
b=['nima','woma','tamad']
dict(zip(a,b))　　　#监制不能重复，唯一性

In [ ]:
from numpy import *

c=array([2,4,8])
b=c/2
k=mat([[0,236,508,131,507,44],[480,236,508,131,507,44],[960,236,316,131,315,44],[0,236,644,141,511,38],[608,236,572,141,453,38]])
k/1.25

In [ ]:
k1=mat([[1144,236,132,141,104,38],[0,230,812,159,509,34],[768,230,508,159,319,34],[0,226,1020,184,509,31]])
k1/1.25

In [ ]:
k2=mat([[968,226,308,184,153,31],[0,216,1020,212,404,29],[960,216,316,212,125,29],[0,204,1020,252,320,27]])
k2/1.25

In [ ]:
k3=mat([[944,204,332,252,104,27],[0,186,1020,308,255,26],[920,186,356,308,89,26],[0,166,1020,368,203,25]])
k3/1.25

In [ ]:
k4=mat([[896,166,380,368,76,25],[0,136,1020,458,161,25],[864,136,412,458,65,25],[0,100,1020,568,128,24]])
k4/1.25

In [ ]:
k5=mat([[824,100,452,568,57,24],[0,52,1020,666,102,22],[776,52,500,666,50,22]])
k5/1.25

In [ ]:
rsr1=mat([[600,4,644,452,203,71],[40,4,644,452,203,71],[608,4,636,452,252,89],[40,4,636,452,252,89]])
rsr1/1.25


In [ ]:
rsr2=mat([[616,60,628,398,313,98],[40,60,628,398,313,98],[624,124,620,334,390,106],[40,124,628,334,395,106]])
rsr2/1.25

In [4]:
str='https://www.guahao.com/department/125809921947822000?isStd='
print(str.split('department/')[1].split('?')[0])
print(str.replace('department/','').replace("https://www.guahao.com/",''))


125809921947822000
125809921947822000?isStd=


In [ ]:
a={1,2,3,4} #这个里面是set
b='wori'
a.add(b) #字典往里面加，和list append差不多
a
for i in a:
    print(i)

In [ ]:
for i in range(1,36):
    print(i)

In [2]:
import datetime
now=datetime.datetime.now().strftime('%Y-%m-%d')
rubtime=now+'12:46'
nownew=datetime.datetime.now().strftime('%Y-%m-%d%H:%M')
print(nownew)
#while True:
    
    
    
     

2019-02-1317:28


In [ ]:
import json
b=json.loads(a)  #转化为ｊｓｏｎ格式
for value in b.values():　　#遍历ｖａｌｕｅｓ
    print(value)

'username' in value　　#判断这个ｖａｌｕｅ在不在里面，ｂｏｏｌ值

In [ ]:
zip(*loc[::-1]) #这个函数的意思，×：代表可变参数，意思调用这个zip函数的时候，传入任意个数目参数
#可以是多个，也可以是0个

In [3]:
# python eval 函数,去掉“”符号
"""
function: transfer str into any of tuple,dict,and list type of datas
see eg
etcs
"""
a = "[[1,2], [3,4], [5,6], [7,8], [9,0]]"
b=eval(a)
print(b)
c="{1: 'a', 2: 'b'}"
d=eval(c)
print(d)

[[1, 2], [3, 4], [5, 6], [7, 8], [9, 0]]
{1: 'a', 2: 'b'}


In [1]:
import numpy as np
a=[1,43,4325,23,3535,23535,23,45,654,6,6,575,8,8]
index=np.argsort(a) #代表从小到大排序
print(index)

index=index[-1:-4:-1]  #代表倒着取3个数，每次间隔为1
print(index)
matrixtest=np.zeros((2,5))  #生成2行5列的0
print(matrixtest)

[ 0  9 10 12 13  3  6  1  7 11  8  4  2  5]
[5 2 4]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [1]:
#创建字典,由list到dict

b=['wocoa','ni','erbi']
c=[2,3,4]
d=dict(zip(b,c))
print(d)

{'wocoa': 2, 'erbi': 4, 'ni': 3}


In [15]:
import numpy as np

a = np.array(range(30)).reshape(2, 3, 5) #生成一个三维数组
#print(a)

#比如要索引13，也就是第一个元素，第3行，第4个元素，就要如下所写
a[0][2][3]
print(a.transpose()) #这个和print(a.transpose(2,1,0))相同

[[[ 0 15]
  [ 5 20]
  [10 25]]

 [[ 1 16]
  [ 6 21]
  [11 26]]

 [[ 2 17]
  [ 7 22]
  [12 27]]

 [[ 3 18]
  [ 8 23]
  [13 28]]

 [[ 4 19]
  [ 9 24]
  [14 29]]]


In [3]:
#正则表达式的例子
import re
a='< path d=" Mo1 c 0 z"/>'   
b=re.findall('< path d="'+'(.*?)''\"',a)[0]
print(b)

 Mo1 c 0 z


In [3]:
#下面是对角矩阵的建立和取列运算实例
import numpy as np

data=np.mat(np.random.randint(0,10,size=[4,4]))
print(data)
print(np.mean(data[:,-2])) #取倒数第二列

#print(np.var(data[:,-1])*np.shape(data)[0])
#print(np.shape(data)[1])
#print(set(data[:,-1].T.tolist()[0]))  #set集合作用只保留不重复的特征值
print(np.power(data[:,-1]-1,2))  #power为平方计算

[[5 9 3 0]
 [0 9 1 6]
 [5 7 1 5]
 [3 4 3 5]]
2.0
[[ 1]
 [25]
 [16]
 [16]]


In [6]:
a ="string"
print("dd%s"(a))

TypeError: 'str' object is not callable